baseURL = 'https://meatlesstrainer.github.io'
languageCode = 'en-us'
title = 'Meatless Trainer'
description = 'The life of a vegan triathlete-in-training.'
theme = 'mini'

[params]
bio = 'The life of a vegan triathlete-in-training.'
